package com.foodie.user;
import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.http.*;import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import java.nio.charset.StandardCharsets;import java.util.Base64;
@RestController @RequestMapping("/api") class UserController{
 private final CustomerRepository repo;private final BCryptPasswordEncoder encoder=new BCryptPasswordEncoder();UserController(CustomerRepository r){repo=r;}
 record Register(@NotBlank String name,@Email @NotBlank String email,@NotBlank String phone,@NotBlank String address,@Size(min=8,max=72) @NotBlank String password){} record Login(@Email @NotBlank String email,@NotBlank String password){} record View(Long customerId,String name,String email,String phone,String address){} record Token(Long customerId,String token,String tokenType){}
 private View view(Customer c){return new View(c.customerId,c.name,c.email,c.phone,c.address);}
 @PostMapping("/users") ResponseEntity<View> register(@Valid @RequestBody Register x){if(repo.existsByEmailIgnoreCase(x.email()))throw new ResponseStatusException(HttpStatus.CONFLICT,"Email is already registered");Customer c=new Customer();c.name=x.name();c.email=x.email().toLowerCase();c.phone=x.phone();c.address=x.address();c.passwordHash=encoder.encode(x.password());return ResponseEntity.status(201).body(view(repo.save(c)));}
 @PostMapping("/login") Token login(@Valid @RequestBody Login x){Customer c=repo.findByEmailIgnoreCase(x.email()).orElseThrow(()->new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid email or password"));if(!encoder.matches(x.password(),c.passwordHash))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid email or password");String token=Base64.getUrlEncoder().withoutPadding().encodeToString((c.customerId+":"+System.currentTimeMillis()).getBytes(StandardCharsets.UTF_8));return new Token(c.customerId,token,"Demo");}
 @GetMapping("/users/{id}") View get(@PathVariable Long id){return view(repo.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"User not found")));}
}
