package com.foodie.order;
import jakarta.transaction.Transactional;import org.springframework.http.*;import org.springframework.stereotype.Service;import org.springframework.web.server.ResponseStatusException;import java.math.BigDecimal;import java.time.LocalDateTime;import java.util.*;
@Service class OrderManager{private final OrderRepository orders;private final CartRepository carts;private final RemoteClients remote;OrderManager(OrderRepository o,CartRepository c,RemoteClients r){orders=o;carts=c;remote=r;}
 record LineRequest(Long dishId,int quantity){} record CreateRequest(Long customerId,Long restaurantId,List<LineRequest> items){} record ItemView(Long orderItemId,Long dishId,String dishName,int quantity,BigDecimal price,BigDecimal subtotal){} record OrderView(Long orderId,Long customerId,Long restaurantId,LocalDateTime orderDate,BigDecimal totalAmount,OrderStatus status,List<ItemView> items){} record CartLine(Long dishId,String dishName,int quantity,BigDecimal unitPrice,BigDecimal subtotal){} record CartView(Long customerId,List<CartLine> items,BigDecimal total){}
 @Transactional OrderView create(CreateRequest x){if(x.customerId()==null||x.restaurantId()==null)bad("Customer and restaurant are required");remote.requireUser(x.customerId());if(x.items()==null||x.items().isEmpty())bad("Order items are required");Set<Long> seen=new HashSet<>();CustomerOrder o=new CustomerOrder();o.customerId=x.customerId();o.restaurantId=x.restaurantId();o.orderDate=LocalDateTime.now();o.status=OrderStatus.PLACED;o.totalAmount=BigDecimal.ZERO;for(LineRequest line:x.items()){if(line.dishId()==null||line.quantity()<1)bad("Dish and positive quantity are required");if(!seen.add(line.dishId()))bad("An order cannot contain duplicate dishes");var d=remote.dish(line.dishId());if(!d.restaurantId().equals(x.restaurantId()))bad("All dishes must belong to the selected restaurant");OrderItem i=new OrderItem();i.dishId=d.dishId();i.dishName=d.name();i.quantity=line.quantity();i.price=d.price();o.add(i);o.totalAmount=o.totalAmount.add(i.price.multiply(BigDecimal.valueOf(i.quantity)));}return view(orders.save(o));}
 @Transactional OrderView get(Long id){return view(orders.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Order not found")));}
 @Transactional OrderView checkout(Long id){var lines=carts.findByCustomerId(id);if(lines.isEmpty())bad("Cart is empty");var order=create(new CreateRequest(id,lines.get(0).restaurantId,lines.stream().map(i->new LineRequest(i.dishId,i.quantity)).toList()));carts.deleteByCustomerId(id);return order;}
 @Transactional CartView add(Long customerId,LineRequest x){remote.requireUser(customerId);if(x.dishId()==null||x.quantity()<1)bad("Dish and positive quantity are required");var d=remote.dish(x.dishId());var existingItems=carts.findByCustomerId(customerId);if(!existingItems.isEmpty()&&!existingItems.get(0).restaurantId.equals(d.restaurantId()))bad("A cart may contain dishes from one restaurant only");CartItem item=carts.findByCustomerIdAndDishId(customerId,x.dishId()).orElseGet(CartItem::new);item.customerId=customerId;item.dishId=d.dishId();item.restaurantId=d.restaurantId();item.dishName=d.name();item.unitPrice=d.price();item.quantity+=x.quantity();carts.save(item);return cart(customerId);}
 CartView cart(Long id){remote.requireUser(id);List<CartLine> lines=carts.findByCustomerId(id).stream().map(i->new CartLine(i.dishId,i.dishName,i.quantity,i.unitPrice,i.unitPrice.multiply(BigDecimal.valueOf(i.quantity)))).toList();return new CartView(id,lines,lines.stream().map(CartLine::subtotal).reduce(BigDecimal.ZERO,BigDecimal::add));}
 @Transactional void clear(Long id){remote.requireUser(id);carts.deleteByCustomerId(id);}
 private OrderView view(CustomerOrder o){return new OrderView(o.orderId,o.customerId,o.restaurantId,o.orderDate,o.totalAmount,o.status,o.items.stream().map(i->new ItemView(i.orderItemId,i.dishId,i.dishName,i.quantity,i.price,i.price.multiply(BigDecimal.valueOf(i.quantity)))).toList());}private void bad(String m){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}
}
