server:
  port: ${SERVER_PORT:8082}
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://food-db:3306/food_db?serverTimezone=UTC}
    username: ${DB_USER:foodie}
    password: ${DB_PASSWORD:foodie}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      mode: always
